version: 2
jobs:
  a:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  b:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more fimiliar hi"
      - run: sleep 15
workflows:
  version: 2
  a_and_b:
    jobs:
      - one
      - two